#!/usr/bin/env bash

count=0

disconnected="睊"
wireless_connected="直"
ethernet_connected="囹"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
	r=$(wget -q --spider www.someurl.com)
	if [ $? = 0 ] ; then 
		if [[ $ID == e* ]]; then
            echo "%{F#00ff00}$ethernet_connected" ; sleep 25
        else
            echo "%{F#00ff00}$wireless_connected" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 0.5
    fi
done
